# Generated by Django 4.2 on 2023-05-05 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RobotCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_category_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_id', models.CharField(max_length=100, null=True)),
                ('robot_name', models.CharField(max_length=100, null=True)),
                ('ram', models.CharField(max_length=150, null=True)),
                ('speed', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(null=True)),
                ('manufacturing_date', models.DateField(null=True)),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='made_in', to='app.manufacturer')),
                ('robot_category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app.robotcategory')),
            ],
        ),
    ]
